library(tidyverse)
library(tidytext)
library(dplyr)
library(readr)
library(tidyr)
library(writexl)
library(readxl)
library(textdata)
library(ggplot2)
library(scales)
library(wordcloud2)
Bootcamp_19 <- read_excel("~/Documents/GitHub/EQuIPD_Teacher_Survey/data/01_2019 Summer Bootcamp.xlsx")
Bootcamp_19Sel<- select(Bootcamp_19, Q5)
remove_words <-data.frame("word"= c("lot", "um", "it's","it", "uh", "ive", "that's","and","N/A","an","a","null","the","n","on","to","i","of","with","liked","about","things","NA","using","worked","was","I", "in","for", "well","time", "enjoyed")) 
Bootcamp_19Rsel<-unnest_tokens(Bootcamp_19Sel, word, Q5) 
Bootcamp_19Rem<- anti_join(Bootcamp_19Rsel,remove_words)
Bootcamp19count <- count(Bootcamp_19Rem, word, sort = TRUE)
wordcloud2(Bootcamp19count)
afinn <- get_sentiments("afinn")
bing <- get_sentiments("bing")
nrc <- get_sentiments("nrc")
loughran <- get_sentiments("loughran")
sentiment_afinn <- inner_join(Bootcamp_19Rem, afinn, by = "word")
sentiment_bing <- inner_join(Bootcamp_19Rem, bing, by = "word")
sentiment_nrc <- inner_join(Bootcamp_19Rem, nrc, by = "word")
sentiment_loughran <- inner_join(Bootcamp_19Rem, loughran, by = "word")
